export interface Ingredient {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  defaultWeight: number;
  baseTime: number;
  timePer100g: number;
  method: string;
  temp?: number;
  tips: string[];
  emoji: string;
  image_url?: string;
}

const INGREDIENT_IMAGES: Record<string, string> = {
  "boeuf-rotis": "/ingredients/boeuf-rotis.jpg",
  "boeuf-entrecote": "/ingredients/boeuf-entrecote.jpg",
  "boeuf-faux-filet": "/ingredients/boeuf-faux-filet.jpg",
  "boeuf-tournedos": "/ingredients/boeuf-tournedos.jpg",
  "boeuf-bavette": "/ingredients/boeuf-bavette.jpg",
  "boeuf-onglet": "/ingredients/boeuf-onglet.jpg",
  "boeuf-hampe": "/ingredients/boeuf-hampe.jpg",
  "boeuf-bourguignon": "/ingredients/boeuf-bourguignon.jpg",
  "boeuf-pot-au-feu": "/ingredients/boeuf-pot-au-feu.jpg",
  "boeuf-steak-hache": "/ingredients/boeuf-steak-hache.jpg",
  "veau-escalope": "/ingredients/veau-escalope.jpg",
  "veau-blanquette": "/ingredients/veau-blanquette.jpg",
  "veau-roti": "/ingredients/veau-roti.jpg",
  "veau-osso-bucco": "/ingredients/veau-osso-bucco.jpg",
  "veau-cote": "/ingredients/veau-cote.jpg",
  "veau-foie": "/ingredients/veau-foie.jpg",
  "porc-cote": "/ingredients/porc-cote.jpg",
  "porc-filet-mignon": "/ingredients/porc-filet-mignon.jpg",
  "porc-roti": "/ingredients/porc-roti.jpg",
  "porc-travers": "/ingredients/porc-travers.jpg",
  "porc-echine": "/ingredients/porc-echine.jpg",
  "porc-lard": "/ingredients/porc-lard.jpg",
  "jambon": "/ingredients/jambon.jpg",
  "saucisse-fraiche": "/ingredients/saucisse-fraiche.jpg",
  "boudin-noir": "/ingredients/boudin-noir.jpg",
  "agneau-gigot": "/ingredients/agneau-gigot.jpg",
  "agneau-cote": "/ingredients/agneau-cote.jpg",
  "agneau-epaule": "/ingredients/agneau-epaule.jpg",
  "agneau-souris": "/ingredients/agneau-souris.jpg",
  "agneau-carre": "/ingredients/agneau-carre.jpg",
  "poulet-entier": "/ingredients/poulet-entier.jpg",
  "poulet-cuisse": "/ingredients/poulet-cuisse.jpg",
  "poulet-filet": "/ingredients/poulet-filet.jpg",
  "poulet-aile": "/ingredients/poulet-aile.jpg",
  "dinde-escalope": "/ingredients/dinde-escalope.jpg",
  "dinde-cuisse": "/ingredients/dinde-cuisse.jpg",
  "dinde-entiere": "/ingredients/dinde-entiere.jpg",
  "magret-canard": "/ingredients/magret-canard.jpg",
  "canard-cuisse": "/ingredients/canard-cuisse.jpg",
  "canard-entier": "/ingredients/canard-entier.jpg",
  "pintade": "/ingredients/pintade.jpg",
  "lapin-entier": "/ingredients/lapin-entier.jpg",
  "saumon-pave": "/ingredients/saumon-pave.jpg",
  "saumon-entier": "/ingredients/saumon-entier.jpg",
  "saumon-fume": "/ingredients/saumon-fume.jpg",
  "cabillaud-filet": "/ingredients/cabillaud-filet.jpg",
  "cabillaud-dos": "/ingredients/cabillaud-dos.jpg",
  "sole": "/ingredients/sole.jpg",
  "bar-loup": "/ingredients/bar-loup.jpg",
  "bar-filet": "/ingredients/bar-filet.jpg",
  "dorade": "/ingredients/dorade.jpg",
  "thon-steak": "/ingredients/thon-steak.jpg",
  "truite": "/ingredients/truite.jpg",
  "maquereau": "/ingredients/maquereau.jpg",
  "sardine": "/ingredients/sardine.jpg",
  "colin": "/ingredients/colin.jpg",
  "lieu-noir": "/ingredients/lieu-noir.jpg",
  "lotte": "/ingredients/lotte.jpg",
  "crevettes": "/ingredients/crevettes.jpg",
  "gambas": "/ingredients/gambas.jpg",
  "langoustines": "/ingredients/langoustines.jpg",
  "homard": "/ingredients/homard.jpg",
  "moules": "/ingredients/moules.jpg",
  "huitres": "/ingredients/huitres.jpg",
  "coquilles-st-jacques": "/ingredients/coquilles-st-jacques.jpg",
  "calamars": "/ingredients/calamars.jpg",
  "poulpe": "/ingredients/poulpe.jpg",
  "carottes-vapeur": "/ingredients/carottes-vapeur.jpg",
  "pommes-terre-eau": "/ingredients/pommes-terre-eau.jpg",
  "pommes-terre-four": "/ingredients/pommes-terre-four.jpg",
  "frites": "/ingredients/frites.jpg",
  "patate-douce": "/ingredients/patate-douce.jpg",
  "courgettes": "/ingredients/courgettes.jpg",
  "aubergines": "/ingredients/aubergines.jpg",
  "poivrons": "/ingredients/poivrons.jpg",
  "tomates": "/ingredients/tomates.jpg",
  "tomates-farcies": "/ingredients/tomates-farcies.jpg",
  "brocolis": "/ingredients/brocolis.jpg",
  "chou-fleur": "/ingredients/chou-fleur.jpg",
  "chou-vert": "/ingredients/chou-vert.jpg",
  "choux-bruxelles": "/ingredients/choux-bruxelles.jpg",
  "haricots-verts": "/ingredients/haricots-verts.jpg",
  "petits-pois": "/ingredients/petits-pois.jpg",
  "feves": "/ingredients/feves.jpg",
  "epinards": "/ingredients/epinards.jpg",
  "asperges-vertes": "/ingredients/asperges-vertes.jpg",
  "artichaut-entier": "/ingredients/artichaut-entier.jpg",
  "champignons": "/ingredients/champignons.jpg",
  "poireaux": "/ingredients/poireaux.jpg",
  "oignons": "/ingredients/oignons.jpg",
  "oignons-caramelises": "/ingredients/oignons-caramelises.jpg",
  "echalotes": "/ingredients/echalotes.jpg",
  "ail-confit": "/ingredients/ail-confit.jpg",
  "celeri-rave": "/ingredients/celeri-rave.jpg",
  "betteraves": "/ingredients/betteraves.jpg",
  "navets": "/ingredients/navets.jpg",
  "panais": "/ingredients/panais.jpg",
  "radis": "/ingredients/radis.jpg",
  "concombre": "/ingredients/concombre.jpg",
  "avocat": "/ingredients/avocat.jpg",
  "salade-verte": "/ingredients/salade-verte.jpg",
  "mais-epi": "/ingredients/mais-epi.jpg",
  "potimarron": "/ingredients/potimarron.jpg",
  "courge-butternut": "/ingredients/courge-butternut.jpg",
  "riz-basmati": "/ingredients/riz-basmati.jpg",
  "riz-complet": "/ingredients/riz-complet.jpg",
  "riz-risotto": "/ingredients/riz-risotto.jpg",
  "riz-thai": "/ingredients/riz-thai.jpg",
  "riz-sushi": "/ingredients/riz-sushi.jpg",
  "pates-spaghetti": "/ingredients/pates-spaghetti.jpg",
  "pates-penne": "/ingredients/pates-penne.jpg",
  "pates-tagliatelles": "/ingredients/pates-tagliatelles.jpg",
  "pates-fusilli": "/ingredients/pates-fusilli.jpg",
  "pates-farfalle": "/ingredients/pates-farfalle.jpg",
  "pates-lasagnes": "/ingredients/pates-lasagnes.jpg",
  "pates-ravioli": "/ingredients/pates-ravioli.jpg",
  "pates-gnocchi": "/ingredients/pates-gnocchi.jpg",
  "quinoa": "/ingredients/quinoa.jpg",
  "boulgour": "/ingredients/boulgour.jpg",
  "couscous": "/ingredients/couscous.jpg",
  "semoule": "/ingredients/semoule.jpg",
  "polenta": "/ingredients/polenta.jpg",
  "lentilles-vertes": "/ingredients/lentilles-vertes.jpg",
  "pois-chiches": "/ingredients/pois-chiches.jpg",
  "haricots-blancs": "/ingredients/haricots-blancs.jpg",
  "haricots-rouges": "/ingredients/haricots-rouges.jpg",
  "oeuf-coque": "/ingredients/oeuf-coque.jpg",
  "oeuf-dur": "/ingredients/oeuf-dur.jpg",
  "oeuf-mollet": "/ingredients/oeuf-mollet.jpg",
  "oeuf-poche": "/ingredients/oeuf-poche.jpg",
  "oeuf-plat": "/ingredients/oeuf-plat.jpg",
  "oeufs-brouilles": "/ingredients/oeufs-brouilles.jpg",
  "omelette": "/ingredients/omelette.jpg",
  "frittata": "/ingredients/frittata.jpg",
  "quiche": "/ingredients/quiche.jpg",
  "souffle-fromage": "/ingredients/souffle-fromage.jpg",
  "pommes": "/ingredients/pommes.jpg",
  "pommes-au-four": "/ingredients/pommes-au-four.jpg",
  "pommes-poelees": "/ingredients/pommes-poelees.jpg",
  "compote-pommes": "/ingredients/compote-pommes.jpg",
  "poires": "/ingredients/poires.jpg",
  "poires-pochees": "/ingredients/poires-pochees.jpg",
  "bananes": "/ingredients/bananes.jpg",
  "bananes-flambees": "/ingredients/bananes-flambees.jpg",
  "orange": "/ingredients/orange.jpg",
  "citron": "/ingredients/citron.jpg",
  "fraises": "/ingredients/fraises.jpg",
  "framboises": "/ingredients/framboises.jpg",
  "fruits-rouges": "/ingredients/fruits-rouges.jpg",
  "fruits-rouges-poeles": "/ingredients/fruits-rouges-poeles.jpg",
  "raisins": "/ingredients/raisins.jpg",
  "peches": "/ingredients/peches.jpg",
  "peches-poelees": "/ingredients/peches-poelees.jpg",
  "abricots": "/ingredients/abricots.jpg",
  "abricots-rotis": "/ingredients/abricots-rotis.jpg",
  "mangue": "/ingredients/mangue.jpg",
  "mangue-caramelisee": "/ingredients/mangue-caramelisee.jpg",
  "ananas": "/ingredients/ananas.jpg",
  "ananas-caramelise": "/ingredients/ananas-caramelise.jpg",
  "melon": "/ingredients/melon.jpg",
  "pasteque": "/ingredients/pasteque.jpg",
  "kiwi": "/ingredients/kiwi.jpg",
  "figues": "/ingredients/figues.jpg",
  "figues-roties": "/ingredients/figues-roties.jpg",
  "pruneaux": "/ingredients/pruneaux.jpg",
  "pruneaux-cuits": "/ingredients/pruneaux-cuits.jpg",
  "rhubarbe": "/ingredients/rhubarbe.jpg"
};

function getImageUrl(id: string): string | undefined {
  return INGREDIENT_IMAGES[id];
}

export const CATEGORIES = [
  "Viandes",
  "Poissons",
  "Légumes",
  "Féculents",
  "Oeufs",
  "Fruits"
];

export const INGREDIENTS: Ingredient[] = [
  // ═══════════════════════════════════════════════════════════════
  // VIANDES - BOEUF
  // ═══════════════════════════════════════════════════════════════
  {
    id: "boeuf-rotis",
    name: "Rôti de Boeuf",
    category: "Viandes",
    subcategory: "Boeuf",
    defaultWeight: 1000,
    baseTime: 15,
    timePer100g: 1.5,
    method: "Four",
    temp: 200,
    tips: ["Sortir la viande 30min avant", "Laisser reposer 10min après cuisson"],
    emoji: "🥩"
  },
  {
    id: "boeuf-entrecote",
    name: "Entrecôte",
    category: "Viandes",
    subcategory: "Boeuf",
    defaultWeight: 300,
    baseTime: 3,
    timePer100g: 1,
    method: "Poêle",
    tips: ["Saisir à feu vif", "2-3 min par face pour saignant"],
    emoji: "🥩"
  },
  {
    id: "boeuf-faux-filet",
    name: "Faux-Filet",
    category: "Viandes",
    subcategory: "Boeuf",
    defaultWeight: 250,
    baseTime: 3,
    timePer100g: 1,
    method: "Poêle",
    tips: ["Poêle bien chaude", "Laisser reposer avant de couper"],
    emoji: "🥩"
  },
  {
    id: "boeuf-tournedos",
    name: "Tournedos",
    category: "Viandes",
    subcategory: "Boeuf",
    defaultWeight: 180,
    baseTime: 3,
    timePer100g: 1.5,
    method: "Poêle",
    tips: ["Cuisson rapide", "Servir rosé"],
    emoji: "🥩"
  },
  {
    id: "boeuf-bavette",
    name: "Bavette",
    category: "Viandes",
    subcategory: "Boeuf",
    defaultWeight: 200,
    baseTime: 2,
    timePer100g: 1,
    method: "Poêle",
    tips: ["Cuisson courte", "Couper contre les fibres"],
    emoji: "🥩"
  },
  {
    id: "boeuf-onglet",
    name: "Onglet",
    category: "Viandes",
    subcategory: "Boeuf",
    defaultWeight: 200,
    baseTime: 2,
    timePer100g: 1,
    method: "Poêle",
    tips: ["Servir saignant", "Retirer le nerf central"],
    emoji: "🥩"
  },
  {
    id: "boeuf-hampe",
    name: "Hampe",
    category: "Viandes",
    subcategory: "Boeuf",
    defaultWeight: 200,
    baseTime: 2,
    timePer100g: 1,
    method: "Poêle",
    tips: ["Ne pas trop cuire", "Idéal saignant"],
    emoji: "🥩"
  },
  {
    id: "boeuf-bourguignon",
    name: "Boeuf Bourguignon",
    category: "Viandes",
    subcategory: "Boeuf",
    defaultWeight: 800,
    baseTime: 150,
    timePer100g: 0,
    method: "Cocotte",
    temp: 150,
    tips: ["Cuisson lente", "La viande doit être fondante"],
    emoji: "🥩"
  },
  {
    id: "boeuf-pot-au-feu",
    name: "Pot-au-Feu",
    category: "Viandes",
    subcategory: "Boeuf",
    defaultWeight: 1000,
    baseTime: 180,
    timePer100g: 0,
    method: "Eau",
    tips: ["Cuisson très lente", "Écumer régulièrement"],
    emoji: "🥩"
  },
  {
    id: "boeuf-steak-hache",
    name: "Steak Haché",
    category: "Viandes",
    subcategory: "Boeuf",
    defaultWeight: 125,
    baseTime: 3,
    timePer100g: 2,
    method: "Poêle",
    tips: ["Feu vif", "Ne pas écraser pendant la cuisson"],
    emoji: "🥩"
  },
  
  // ═══════════════════════════════════════════════════════════════
  // VIANDES - VEAU
  // ═══════════════════════════════════════════════════════════════
  {
    id: "veau-escalope",
    name: "Escalope de Veau",
    category: "Viandes",
    subcategory: "Veau",
    defaultWeight: 150,
    baseTime: 3,
    timePer100g: 2,
    method: "Poêle",
    tips: ["Farine légèrement", "Cuisson rapide"],
    emoji: "🍖"
  },
  {
    id: "veau-blanquette",
    name: "Blanquette de Veau",
    category: "Viandes",
    subcategory: "Veau",
    defaultWeight: 800,
    baseTime: 90,
    timePer100g: 0,
    method: "Cocotte",
    tips: ["Ne pas faire bouillir", "Sauce crémeuse"],
    emoji: "🍖"
  },
  {
    id: "veau-roti",
    name: "Rôti de Veau",
    category: "Viandes",
    subcategory: "Veau",
    defaultWeight: 1000,
    baseTime: 20,
    timePer100g: 3,
    method: "Four",
    temp: 180,
    tips: ["Arroser régulièrement", "Servir rosé"],
    emoji: "🍖"
  },
  {
    id: "veau-osso-bucco",
    name: "Osso Bucco",
    category: "Viandes",
    subcategory: "Veau",
    defaultWeight: 400,
    baseTime: 120,
    timePer100g: 0,
    method: "Cocotte",
    tips: ["Cuisson lente", "Servir avec gremolata"],
    emoji: "🍖"
  },
  {
    id: "veau-cote",
    name: "Côte de Veau",
    category: "Viandes",
    subcategory: "Veau",
    defaultWeight: 300,
    baseTime: 6,
    timePer100g: 2,
    method: "Poêle",
    tips: ["Finir au four 10min à 180°C", "Laisser reposer"],
    emoji: "🍖"
  },
  {
    id: "veau-foie",
    name: "Foie de Veau",
    category: "Viandes",
    subcategory: "Veau",
    defaultWeight: 150,
    baseTime: 2,
    timePer100g: 1,
    method: "Poêle",
    tips: ["Cuisson très courte", "Servir rosé à l'intérieur"],
    emoji: "🍖"
  },

  // ═══════════════════════════════════════════════════════════════
  // VIANDES - VOLAILLE
  // ═══════════════════════════════════════════════════════════════
  {
    id: "poulet-entier",
    name: "Poulet Entier",
    category: "Viandes",
    subcategory: "Volaille",
    defaultWeight: 1500,
    baseTime: 20,
    timePer100g: 5,
    method: "Four",
    temp: 180,
    tips: ["Arroser toutes les 20min", "Vérifier la cuisson à la cuisse"],
    emoji: "🍗"
  },
  {
    id: "poulet-cuisse",
    name: "Cuisse de Poulet",
    category: "Viandes",
    subcategory: "Volaille",
    defaultWeight: 200,
    baseTime: 25,
    timePer100g: 5,
    method: "Four",
    temp: 200,
    tips: ["Peau croustillante à 220°C", "Chair bien cuite"],
    emoji: "🍗"
  },
  {
    id: "poulet-filet",
    name: "Filet de Poulet",
    category: "Viandes",
    subcategory: "Volaille",
    defaultWeight: 150,
    baseTime: 8,
    timePer100g: 4,
    method: "Poêle",
    tips: ["Ne pas surcuire", "Couvrir pour garder moelleux"],
    emoji: "🍗"
  },
  {
    id: "poulet-aile",
    name: "Ailes de Poulet",
    category: "Viandes",
    subcategory: "Volaille",
    defaultWeight: 500,
    baseTime: 25,
    timePer100g: 0,
    method: "Four",
    temp: 200,
    tips: ["Retourner à mi-cuisson", "Marinade recommandée"],
    emoji: "🍗"
  },
  {
    id: "dinde-escalope",
    name: "Escalope de Dinde",
    category: "Viandes",
    subcategory: "Volaille",
    defaultWeight: 150,
    baseTime: 6,
    timePer100g: 3,
    method: "Poêle",
    tips: ["Feu moyen", "Ne pas surcuire"],
    emoji: "🦃"
  },
  {
    id: "dinde-cuisse",
    name: "Cuisse de Dinde",
    category: "Viandes",
    subcategory: "Volaille",
    defaultWeight: 500,
    baseTime: 45,
    timePer100g: 5,
    method: "Four",
    temp: 180,
    tips: ["Arroser régulièrement", "Bien cuite à coeur"],
    emoji: "🍗"
  },
  {
    id: "dinde-entiere",
    name: "Dinde Entière",
    category: "Viandes",
    subcategory: "Volaille",
    defaultWeight: 4000,
    baseTime: 30,
    timePer100g: 3,
    method: "Four",
    temp: 160,
    tips: ["Farcir pour plus de saveur", "Couvrir d'alu si dore trop"],
    emoji: "🦃"
  },
  {
    id: "magret-canard",
    name: "Magret de Canard",
    category: "Viandes",
    subcategory: "Volaille",
    defaultWeight: 400,
    baseTime: 0,
    timePer100g: 2.5,
    method: "Poêle",
    tips: ["Quadriller la peau", "Commencer côté peau à froid"],
    emoji: "🦆"
  },
  {
    id: "canard-cuisse",
    name: "Cuisse de Canard",
    category: "Viandes",
    subcategory: "Volaille",
    defaultWeight: 250,
    baseTime: 25,
    timePer100g: 0,
    method: "Four",
    temp: 200,
    tips: ["Réchauffer au four", "Peau croustillante"],
    emoji: "🦆"
  },
  {
    id: "canard-entier",
    name: "Canard Entier",
    category: "Viandes",
    subcategory: "Volaille",
    defaultWeight: 2000,
    baseTime: 20,
    timePer100g: 4,
    method: "Four",
    temp: 180,
    tips: ["Piquer la peau", "Arroser avec le jus"],
    emoji: "🍗"
  },
  {
    id: "pintade",
    name: "Pintade",
    category: "Viandes",
    subcategory: "Volaille",
    defaultWeight: 1200,
    baseTime: 15,
    timePer100g: 4,
    method: "Four",
    temp: 180,
    tips: ["Barder pour garder moelleux", "Servir rosé"],
    emoji: "🐔"
  },
  {
    id: "lapin-entier",
    name: "Lapin",
    category: "Viandes",
    subcategory: "Volaille",
    defaultWeight: 1500,
    baseTime: 45,
    timePer100g: 2,
    method: "Four",
    temp: 180,
    tips: ["Arroser de moutarde", "Chair blanche bien cuite"],
    emoji: "🍗"
  },

  // ═══════════════════════════════════════════════════════════════
  // VIANDES - PORC
  // ═══════════════════════════════════════════════════════════════
  {
    id: "porc-roti",
    name: "Rôti de Porc",
    category: "Viandes",
    subcategory: "Porc",
    defaultWeight: 1000,
    baseTime: 25,
    timePer100g: 4,
    method: "Four",
    temp: 180,
    tips: ["Bien cuit à coeur", "Laisser reposer 10min"],
    emoji: "🐷"
  },
  {
    id: "porc-cote",
    name: "Côte de Porc",
    category: "Viandes",
    subcategory: "Porc",
    defaultWeight: 200,
    baseTime: 8,
    timePer100g: 3,
    method: "Poêle",
    tips: ["Feu moyen", "Retourner une fois"],
    emoji: "🐷"
  },
  {
    id: "porc-filet-mignon",
    name: "Filet Mignon de Porc",
    category: "Viandes",
    subcategory: "Porc",
    defaultWeight: 500,
    baseTime: 20,
    timePer100g: 3,
    method: "Four",
    temp: 180,
    tips: ["Saisir avant", "Enrouler de lard"],
    emoji: "🐷"
  },
  {
    id: "porc-travers",
    name: "Travers de Porc",
    category: "Viandes",
    subcategory: "Porc",
    defaultWeight: 1000,
    baseTime: 90,
    timePer100g: 0,
    method: "Four",
    temp: 160,
    tips: ["Cuisson lente", "Badigeonner de sauce BBQ"],
    emoji: "🐷"
  },
  {
    id: "porc-echine",
    name: "Échine de Porc",
    category: "Viandes",
    subcategory: "Porc",
    defaultWeight: 1000,
    baseTime: 30,
    timePer100g: 4,
    method: "Four",
    temp: 170,
    tips: ["Grasse et savoureuse", "Effilochée après cuisson longue"],
    emoji: "🐷"
  },
  {
    id: "porc-lard",
    name: "Lardons",
    category: "Viandes",
    subcategory: "Porc",
    defaultWeight: 200,
    baseTime: 8,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Feu moyen", "Bien dorés"],
    emoji: "🐷"
  },
  {
    id: "saucisse-fraiche",
    name: "Saucisse Fraîche",
    category: "Viandes",
    subcategory: "Porc",
    defaultWeight: 150,
    baseTime: 15,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Feu doux", "Piquer légèrement"],
    emoji: "🌭"
  },
  {
    id: "boudin-noir",
    name: "Boudin Noir",
    category: "Viandes",
    subcategory: "Porc",
    defaultWeight: 200,
    baseTime: 10,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Feu très doux", "Ne pas percer la peau"],
    emoji: "🌭"
  },
  {
    id: "jambon",
    name: "Jambon",
    category: "Viandes",
    subcategory: "Porc",
    defaultWeight: 100,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Servir à température ambiante"],
    emoji: "🥓"
  },

  // ═══════════════════════════════════════════════════════════════
  // VIANDES - AGNEAU
  // ═══════════════════════════════════════════════════════════════
  {
    id: "agneau-gigot",
    name: "Gigot d'Agneau",
    category: "Viandes",
    subcategory: "Agneau",
    defaultWeight: 2000,
    baseTime: 20,
    timePer100g: 3,
    method: "Four",
    temp: 200,
    tips: ["Piquer d'ail", "Servir rosé"],
    emoji: "🐑"
  },
  {
    id: "agneau-cote",
    name: "Côtelettes d'Agneau",
    category: "Viandes",
    subcategory: "Agneau",
    defaultWeight: 100,
    baseTime: 4,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Feu vif", "Servir rosé"],
    emoji: "🐑"
  },
  {
    id: "agneau-carre",
    name: "Carré d'Agneau",
    category: "Viandes",
    subcategory: "Agneau",
    defaultWeight: 800,
    baseTime: 25,
    timePer100g: 0,
    method: "Four",
    temp: 200,
    tips: ["Saisir avant", "Chair rosée"],
    emoji: "🐑"
  },
  {
    id: "agneau-epaule",
    name: "Épaule d'Agneau",
    category: "Viandes",
    subcategory: "Agneau",
    defaultWeight: 1500,
    baseTime: 150,
    timePer100g: 0,
    method: "Four",
    temp: 150,
    tips: ["Cuisson lente", "Viande confite"],
    emoji: "🐑"
  },
  {
    id: "agneau-souris",
    name: "Souris d'Agneau",
    category: "Viandes",
    subcategory: "Agneau",
    defaultWeight: 350,
    baseTime: 120,
    timePer100g: 0,
    method: "Cocotte",
    tips: ["Braiser doucement", "Chair fondante"],
    emoji: "🐑"
  },

  // ═══════════════════════════════════════════════════════════════
  // POISSONS - GRAS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "saumon-pave",
    name: "Pavé de Saumon",
    category: "Poissons",
    subcategory: "Poisson Gras",
    defaultWeight: 150,
    baseTime: 0,
    timePer100g: 8,
    method: "Poêle",
    tips: ["Cuire côté peau", "Feu moyen"],
    emoji: "🍣"
  },
  {
    id: "saumon-entier",
    name: "Saumon Entier",
    category: "Poissons",
    subcategory: "Poisson Gras",
    defaultWeight: 2000,
    baseTime: 10,
    timePer100g: 2,
    method: "Four",
    temp: 180,
    tips: ["En papillote ou court-bouillon", "Chair rosée à coeur"],
    emoji: "🐟"
  },
  {
    id: "saumon-fume",
    name: "Saumon Fumé",
    category: "Poissons",
    subcategory: "Poisson Gras",
    defaultWeight: 100,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Servir à température", "Avec blinis et crème"],
    emoji: "🍣"
  },
  {
    id: "thon-steak",
    name: "Steak de Thon",
    category: "Poissons",
    subcategory: "Poisson Gras",
    defaultWeight: 180,
    baseTime: 2,
    timePer100g: 1,
    method: "Poêle",
    tips: ["Cuisson mi-cuit", "Feu très vif"],
    emoji: "🐟"
  },
  {
    id: "maquereau",
    name: "Maquereau",
    category: "Poissons",
    subcategory: "Poisson Gras",
    defaultWeight: 250,
    baseTime: 8,
    timePer100g: 2,
    method: "Grill",
    tips: ["Inciser la peau", "Feu vif"],
    emoji: "🐟"
  },
  {
    id: "sardine",
    name: "Sardines",
    category: "Poissons",
    subcategory: "Poisson Gras",
    defaultWeight: 200,
    baseTime: 4,
    timePer100g: 0,
    method: "Grill",
    tips: ["3 min par face", "Huile d'olive et gros sel"],
    emoji: "🐟"
  },
  {
    id: "truite",
    name: "Truite",
    category: "Poissons",
    subcategory: "Poisson Gras",
    defaultWeight: 300,
    baseTime: 10,
    timePer100g: 2,
    method: "Poêle",
    tips: ["Cuisson meunière", "Beurre noisette"],
    emoji: "🐟"
  },

  // ═══════════════════════════════════════════════════════════════
  // POISSONS - BLANCS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "cabillaud-dos",
    name: "Dos de Cabillaud",
    category: "Poissons",
    subcategory: "Poisson Blanc",
    defaultWeight: 150,
    baseTime: 0,
    timePer100g: 10,
    method: "Four",
    temp: 180,
    tips: ["Filet d'huile d'olive", "Ne pas surcuire"],
    emoji: "🐟"
  },
  {
    id: "cabillaud-filet",
    name: "Filet de Cabillaud",
    category: "Poissons",
    subcategory: "Poisson Blanc",
    defaultWeight: 150,
    baseTime: 8,
    timePer100g: 3,
    method: "Vapeur",
    tips: ["Cuisson délicate", "Chair blanche et moelleuse"],
    emoji: "🐟"
  },
  {
    id: "lieu-noir",
    name: "Lieu Noir",
    category: "Poissons",
    subcategory: "Poisson Blanc",
    defaultWeight: 150,
    baseTime: 8,
    timePer100g: 3,
    method: "Poêle",
    tips: ["Économique et savoureux", "Bien assaisonner"],
    emoji: "🐟"
  },
  {
    id: "colin",
    name: "Colin (Merlu)",
    category: "Poissons",
    subcategory: "Poisson Blanc",
    defaultWeight: 150,
    baseTime: 10,
    timePer100g: 3,
    method: "Vapeur",
    tips: ["Chair fine", "Sauce légère"],
    emoji: "🐟"
  },
  {
    id: "sole",
    name: "Sole",
    category: "Poissons",
    subcategory: "Poisson Blanc",
    defaultWeight: 300,
    baseTime: 6,
    timePer100g: 2,
    method: "Poêle",
    tips: ["Cuisson meunière", "Beurre citronné"],
    emoji: "🐟"
  },
  {
    id: "bar-loup",
    name: "Bar (Loup)",
    category: "Poissons",
    subcategory: "Poisson Blanc",
    defaultWeight: 400,
    baseTime: 20,
    timePer100g: 0,
    method: "Four",
    temp: 180,
    tips: ["En croûte de sel", "Chair délicate"],
    emoji: "🐟"
  },
  {
    id: "bar-filet",
    name: "Filet de Bar",
    category: "Poissons",
    subcategory: "Poisson Blanc",
    defaultWeight: 150,
    baseTime: 6,
    timePer100g: 2,
    method: "Poêle",
    tips: ["Côté peau d'abord", "Peau croustillante"],
    emoji: "🐟"
  },
  {
    id: "dorade",
    name: "Dorade",
    category: "Poissons",
    subcategory: "Poisson Blanc",
    defaultWeight: 400,
    baseTime: 25,
    timePer100g: 0,
    method: "Four",
    temp: 200,
    tips: ["Entière avec herbes", "Citron et huile d'olive"],
    emoji: "🐟"
  },
  {
    id: "lotte",
    name: "Lotte (Queue)",
    category: "Poissons",
    subcategory: "Poisson Blanc",
    defaultWeight: 300,
    baseTime: 15,
    timePer100g: 3,
    method: "Four",
    temp: 180,
    tips: ["Chair ferme comme homard", "Rôtir entière"],
    emoji: "🐟"
  },

  // ═══════════════════════════════════════════════════════════════
  // POISSONS - FRUITS DE MER
  // ═══════════════════════════════════════════════════════════════
  {
    id: "crevettes",
    name: "Crevettes",
    category: "Poissons",
    subcategory: "Fruits de Mer",
    defaultWeight: 200,
    baseTime: 3,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Feu vif", "Retirer dès qu'elles rosissent"],
    emoji: "🦐"
  },
  {
    id: "gambas",
    name: "Gambas",
    category: "Poissons",
    subcategory: "Fruits de Mer",
    defaultWeight: 200,
    baseTime: 4,
    timePer100g: 0,
    method: "Grill",
    tips: ["À la plancha", "Huile d'olive et ail"],
    emoji: "🦐"
  },
  {
    id: "langoustines",
    name: "Langoustines",
    category: "Poissons",
    subcategory: "Fruits de Mer",
    defaultWeight: 300,
    baseTime: 3,
    timePer100g: 0,
    method: "Eau",
    tips: ["Court-bouillon", "Ne pas surcuire"],
    emoji: "🦐"
  },
  {
    id: "homard",
    name: "Homard",
    category: "Poissons",
    subcategory: "Fruits de Mer",
    defaultWeight: 600,
    baseTime: 15,
    timePer100g: 2,
    method: "Eau",
    tips: ["Court-bouillon parfumé", "12min/500g"],
    emoji: "🦞"
  },
  {
    id: "moules",
    name: "Moules",
    category: "Poissons",
    subcategory: "Fruits de Mer",
    defaultWeight: 500,
    baseTime: 5,
    timePer100g: 0,
    method: "Cocotte",
    tips: ["Marinières ou à la crème", "Retirer celles fermées"],
    emoji: "🦪"
  },
  {
    id: "coquilles-st-jacques",
    name: "Saint-Jacques",
    category: "Poissons",
    subcategory: "Fruits de Mer",
    defaultWeight: 200,
    baseTime: 2,
    timePer100g: 0,
    method: "Poêle",
    tips: ["1-2 min par face", "Feu vif, coeur nacré"],
    emoji: "🐚"
  },
  {
    id: "calamars",
    name: "Calamars",
    category: "Poissons",
    subcategory: "Fruits de Mer",
    defaultWeight: 300,
    baseTime: 2,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Cuisson très courte ou très longue", "Éviter entre-deux"],
    emoji: "🦑"
  },
  {
    id: "poulpe",
    name: "Poulpe",
    category: "Poissons",
    subcategory: "Fruits de Mer",
    defaultWeight: 500,
    baseTime: 45,
    timePer100g: 0,
    method: "Eau",
    tips: ["Cuisson longue pour attendrir", "Ajouter bouchon liège"],
    emoji: "🐙"
  },
  {
    id: "huitres",
    name: "Huîtres",
    category: "Poissons",
    subcategory: "Fruits de Mer",
    defaultWeight: 150,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Servir fraîches", "Citron ou vinaigre échalote"],
    emoji: "🦪"
  },

  // ═══════════════════════════════════════════════════════════════
  // LÉGUMES - VERTS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "haricots-verts",
    name: "Haricots Verts",
    category: "Légumes",
    subcategory: "Légumes Verts",
    defaultWeight: 500,
    baseTime: 12,
    timePer100g: 0,
    method: "Vapeur",
    tips: ["Plonger dans eau glacée après cuisson"],
    emoji: "🫛"
  },
  {
    id: "petits-pois",
    name: "Petits Pois",
    category: "Légumes",
    subcategory: "Légumes Verts",
    defaultWeight: 300,
    baseTime: 8,
    timePer100g: 0,
    method: "Eau",
    tips: ["Frais: 8-10min, surgelés: 5min"],
    emoji: "🫛"
  },
  {
    id: "epinards",
    name: "Épinards",
    category: "Légumes",
    subcategory: "Légumes Verts",
    defaultWeight: 500,
    baseTime: 3,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Tombent très vite", "Égoutter bien"],
    emoji: "🥬"
  },
  {
    id: "brocolis",
    name: "Brocolis",
    category: "Légumes",
    subcategory: "Légumes Verts",
    defaultWeight: 500,
    baseTime: 8,
    timePer100g: 0,
    method: "Vapeur",
    tips: ["Couper en fleurettes égales"],
    emoji: "🥦"
  },
  {
    id: "chou-fleur",
    name: "Chou-Fleur",
    category: "Légumes",
    subcategory: "Légumes Verts",
    defaultWeight: 600,
    baseTime: 15,
    timePer100g: 0,
    method: "Eau",
    tips: ["Entier ou en fleurettes"],
    emoji: "🥦"
  },
  {
    id: "choux-bruxelles",
    name: "Choux de Bruxelles",
    category: "Légumes",
    subcategory: "Légumes Verts",
    defaultWeight: 400,
    baseTime: 15,
    timePer100g: 0,
    method: "Eau",
    tips: ["Inciser la base", "Eau salée"],
    emoji: "🥬"
  },
  {
    id: "asperges-vertes",
    name: "Asperges Vertes",
    category: "Légumes",
    subcategory: "Légumes Verts",
    defaultWeight: 500,
    baseTime: 8,
    timePer100g: 0,
    method: "Eau",
    tips: ["Debout dans l'eau", "Pointes hors de l'eau"],
    emoji: "🌿"
  },
  {
    id: "poireaux",
    name: "Poireaux",
    category: "Légumes",
    subcategory: "Légumes Verts",
    defaultWeight: 400,
    baseTime: 15,
    timePer100g: 0,
    method: "Eau",
    tips: ["Bien laver", "Fondants"],
    emoji: "🧅"
  },
  {
    id: "artichaut-entier",
    name: "Artichaut",
    category: "Légumes",
    subcategory: "Légumes Verts",
    defaultWeight: 300,
    baseTime: 40,
    timePer100g: 0,
    method: "Eau",
    tips: ["Gros artichauts", "Retirer le foin"],
    emoji: "🌿"
  },
  {
    id: "salade-verte",
    name: "Salade Verte",
    category: "Légumes",
    subcategory: "Légumes Verts",
    defaultWeight: 200,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Laver et essorer", "Assaisonner au dernier moment"],
    emoji: "🥬"
  },
  {
    id: "chou-vert",
    name: "Chou Vert",
    category: "Légumes",
    subcategory: "Légumes Verts",
    defaultWeight: 500,
    baseTime: 20,
    timePer100g: 0,
    method: "Eau",
    tips: ["Blanchir avant", "Braiser pour plus de saveur"],
    emoji: "🥬"
  },

  // ═══════════════════════════════════════════════════════════════
  // LÉGUMES - RACINES
  // ═══════════════════════════════════════════════════════════════
  {
    id: "pommes-terre-eau",
    name: "Pommes de Terre",
    category: "Légumes",
    subcategory: "Racines",
    defaultWeight: 500,
    baseTime: 20,
    timePer100g: 1,
    method: "Eau",
    tips: ["Démarrer eau froide salée", "Vérifier avec couteau"],
    emoji: "🥔"
  },
  {
    id: "pommes-terre-four",
    name: "Pommes de Terre au Four",
    category: "Légumes",
    subcategory: "Racines",
    defaultWeight: 300,
    baseTime: 45,
    timePer100g: 5,
    method: "Four",
    temp: 200,
    tips: ["Piquer avec fourchette", "Chair farineuse"],
    emoji: "🍎"
  },
  {
    id: "frites",
    name: "Frites",
    category: "Légumes",
    subcategory: "Racines",
    defaultWeight: 500,
    baseTime: 8,
    timePer100g: 0,
    method: "Friture",
    temp: 180,
    tips: ["Double cuisson", "1ère à 160°C, 2ème à 180°C"],
    emoji: "🍟"
  },
  {
    id: "carottes-vapeur",
    name: "Carottes",
    category: "Légumes",
    subcategory: "Racines",
    defaultWeight: 400,
    baseTime: 15,
    timePer100g: 0,
    method: "Vapeur",
    tips: ["Couper en rondelles égales"],
    emoji: "🥕"
  },
  {
    id: "navets",
    name: "Navets",
    category: "Légumes",
    subcategory: "Racines",
    defaultWeight: 400,
    baseTime: 20,
    timePer100g: 0,
    method: "Eau",
    tips: ["Blanchir pour adoucir", "Glacer au beurre"],
    emoji: "🥔"
  },
  {
    id: "panais",
    name: "Panais",
    category: "Légumes",
    subcategory: "Racines",
    defaultWeight: 400,
    baseTime: 20,
    timePer100g: 0,
    method: "Vapeur",
    tips: ["Goût sucré", "Excellent en purée"],
    emoji: "🥕"
  },
  {
    id: "betteraves",
    name: "Betteraves",
    category: "Légumes",
    subcategory: "Racines",
    defaultWeight: 400,
    baseTime: 60,
    timePer100g: 0,
    method: "Four",
    temp: 180,
    tips: ["En papillote", "Éplucher après cuisson"],
    emoji: "🍠"
  },
  {
    id: "patate-douce",
    name: "Patate Douce",
    category: "Légumes",
    subcategory: "Racines",
    defaultWeight: 300,
    baseTime: 20,
    timePer100g: 0,
    method: "Vapeur",
    tips: ["Chair orangée sucrée"],
    emoji: "🍠"
  },
  {
    id: "celeri-rave",
    name: "Céleri-Rave",
    category: "Légumes",
    subcategory: "Racines",
    defaultWeight: 500,
    baseTime: 25,
    timePer100g: 0,
    method: "Eau",
    tips: ["Citronner pour éviter oxydation"],
    emoji: "🥬"
  },
  {
    id: "radis",
    name: "Radis",
    category: "Légumes",
    subcategory: "Racines",
    defaultWeight: 200,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Avec beurre et sel", "Croquants"],
    emoji: "🥕"
  },

  // ═══════════════════════════════════════════════════════════════
  // LÉGUMES - FRUITS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "tomates",
    name: "Tomates",
    category: "Légumes",
    subcategory: "Légumes Fruits",
    defaultWeight: 400,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Servir à température ambiante"],
    emoji: "🍅"
  },
  {
    id: "tomates-farcies",
    name: "Tomates Farcies",
    category: "Légumes",
    subcategory: "Légumes Fruits",
    defaultWeight: 600,
    baseTime: 45,
    timePer100g: 0,
    method: "Four",
    temp: 180,
    tips: ["Farce à la viande", "Arroser du jus"],
    emoji: "🍅"
  },
  {
    id: "courgettes",
    name: "Courgettes",
    category: "Légumes",
    subcategory: "Légumes Fruits",
    defaultWeight: 400,
    baseTime: 8,
    timePer100g: 0,
    method: "Vapeur",
    tips: ["Tranches épaisses", "Garder fermes"],
    emoji: "🥒"
  },
  {
    id: "aubergines",
    name: "Aubergines",
    category: "Légumes",
    subcategory: "Légumes Fruits",
    defaultWeight: 400,
    baseTime: 15,
    timePer100g: 0,
    method: "Grill",
    tips: ["Tranches épaisses", "Huile d'olive généreuse"],
    emoji: "🍆"
  },
  {
    id: "poivrons",
    name: "Poivrons",
    category: "Légumes",
    subcategory: "Légumes Fruits",
    defaultWeight: 400,
    baseTime: 20,
    timePer100g: 0,
    method: "Four",
    temp: 220,
    tips: ["Peau noircie", "Peler sous film"],
    emoji: "🫑"
  },
  {
    id: "champignons",
    name: "Champignons",
    category: "Légumes",
    subcategory: "Légumes Fruits",
    defaultWeight: 300,
    baseTime: 8,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Feu vif", "Ne pas surcharger la poêle"],
    emoji: "🍄"
  },
  {
    id: "mais-epi",
    name: "Maïs en Épi",
    category: "Légumes",
    subcategory: "Légumes Fruits",
    defaultWeight: 200,
    baseTime: 10,
    timePer100g: 0,
    method: "Eau",
    tips: ["Eau non salée", "Beurre salé après"],
    emoji: "🌽"
  },
  {
    id: "courge-butternut",
    name: "Courge Butternut",
    category: "Légumes",
    subcategory: "Légumes Fruits",
    defaultWeight: 500,
    baseTime: 40,
    timePer100g: 0,
    method: "Four",
    temp: 200,
    tips: ["En cubes ou demie", "Chair fondante"],
    emoji: "🎃"
  },
  {
    id: "potimarron",
    name: "Potimarron",
    category: "Légumes",
    subcategory: "Légumes Fruits",
    defaultWeight: 600,
    baseTime: 35,
    timePer100g: 0,
    method: "Four",
    temp: 200,
    tips: ["Peau comestible", "Goût châtaigne"],
    emoji: "🎃"
  },
  {
    id: "concombre",
    name: "Concombre",
    category: "Légumes",
    subcategory: "Légumes Fruits",
    defaultWeight: 300,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Dégorger au sel", "Frais et croquant"],
    emoji: "🥒"
  },
  {
    id: "avocat",
    name: "Avocat",
    category: "Légumes",
    subcategory: "Légumes Fruits",
    defaultWeight: 150,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Mûr à point", "Citronner pour éviter oxydation"],
    emoji: "🥑"
  },

  // ═══════════════════════════════════════════════════════════════
  // LÉGUMES - LÉGUMINEUSES
  // ═══════════════════════════════════════════════════════════════
  {
    id: "lentilles-vertes",
    name: "Lentilles Vertes",
    category: "Légumes",
    subcategory: "Légumineuses",
    defaultWeight: 200,
    baseTime: 25,
    timePer100g: 0,
    method: "Eau",
    tips: ["Ne pas saler au début", "Démarrer eau froide"],
    emoji: "🫘"
  },
  {
    id: "pois-chiches",
    name: "Pois Chiches",
    category: "Légumes",
    subcategory: "Légumineuses",
    defaultWeight: 200,
    baseTime: 90,
    timePer100g: 0,
    method: "Eau",
    tips: ["Trempage 12h", "Bicarbonate accélère"],
    emoji: "🫘"
  },
  {
    id: "haricots-blancs",
    name: "Haricots Blancs",
    category: "Légumes",
    subcategory: "Légumineuses",
    defaultWeight: 200,
    baseTime: 90,
    timePer100g: 0,
    method: "Eau",
    tips: ["Trempage une nuit", "Saler en fin de cuisson"],
    emoji: "🫘"
  },
  {
    id: "haricots-rouges",
    name: "Haricots Rouges",
    category: "Légumes",
    subcategory: "Légumineuses",
    defaultWeight: 200,
    baseTime: 90,
    timePer100g: 0,
    method: "Eau",
    tips: ["Trempage obligatoire", "Bouillir 10min au départ"],
    emoji: "🫘"
  },
  {
    id: "feves",
    name: "Fèves",
    category: "Légumes",
    subcategory: "Légumineuses",
    defaultWeight: 300,
    baseTime: 15,
    timePer100g: 0,
    method: "Eau",
    tips: ["Écosser et peler", "Fraîches: 5min"],
    emoji: "🫛"
  },

  // ═══════════════════════════════════════════════════════════════
  // LÉGUMES - ALLIACÉS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "oignons",
    name: "Oignons",
    category: "Légumes",
    subcategory: "Alliacés",
    defaultWeight: 200,
    baseTime: 10,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Feu moyen", "Translucides ou dorés"],
    emoji: "🧅"
  },
  {
    id: "oignons-caramelises",
    name: "Oignons Caramélisés",
    category: "Légumes",
    subcategory: "Alliacés",
    defaultWeight: 500,
    baseTime: 30,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Feu doux", "Patience pour dorer"],
    emoji: "🧅"
  },
  {
    id: "ail-confit",
    name: "Ail Confit",
    category: "Légumes",
    subcategory: "Alliacés",
    defaultWeight: 100,
    baseTime: 45,
    timePer100g: 0,
    method: "Four",
    temp: 160,
    tips: ["Huile d'olive", "Tête entière"],
    emoji: "🧄"
  },
  {
    id: "echalotes",
    name: "Échalotes",
    category: "Légumes",
    subcategory: "Alliacés",
    defaultWeight: 100,
    baseTime: 5,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Émincer finement", "Ne pas brûler"],
    emoji: "🧅"
  },

  // ═══════════════════════════════════════════════════════════════
  // FÉCULENTS - PÂTES
  // ═══════════════════════════════════════════════════════════════
  {
    id: "pates-spaghetti",
    name: "Spaghetti",
    category: "Féculents",
    subcategory: "Pâtes",
    defaultWeight: 100,
    baseTime: 9,
    timePer100g: 0,
    method: "Eau",
    tips: ["1L d'eau pour 100g", "Saler à l'ébullition"],
    emoji: "🍝"
  },
  {
    id: "pates-penne",
    name: "Penne",
    category: "Féculents",
    subcategory: "Pâtes",
    defaultWeight: 100,
    baseTime: 11,
    timePer100g: 0,
    method: "Eau",
    tips: ["Idéales avec sauces épaisses"],
    emoji: "🍝"
  },
  {
    id: "pates-tagliatelles",
    name: "Tagliatelles",
    category: "Féculents",
    subcategory: "Pâtes",
    defaultWeight: 100,
    baseTime: 8,
    timePer100g: 0,
    method: "Eau",
    tips: ["Fraîches: 2-3min", "Parfaites carbonara"],
    emoji: "🍝"
  },
  {
    id: "pates-fusilli",
    name: "Fusilli",
    category: "Féculents",
    subcategory: "Pâtes",
    defaultWeight: 100,
    baseTime: 10,
    timePer100g: 0,
    method: "Eau",
    tips: ["Retiennent bien la sauce"],
    emoji: "🍝"
  },
  {
    id: "pates-lasagnes",
    name: "Lasagnes",
    category: "Féculents",
    subcategory: "Pâtes",
    defaultWeight: 300,
    baseTime: 45,
    timePer100g: 0,
    method: "Four",
    temp: 180,
    tips: ["Cuisson assemblée", "Pas besoin de précuire"],
    emoji: "🍝"
  },
  {
    id: "pates-gnocchi",
    name: "Gnocchi",
    category: "Féculents",
    subcategory: "Pâtes",
    defaultWeight: 200,
    baseTime: 3,
    timePer100g: 0,
    method: "Eau",
    tips: ["Remontent quand cuits", "Poêler après pour dorer"],
    emoji: "🍝"
  },
  {
    id: "pates-ravioli",
    name: "Raviolis",
    category: "Féculents",
    subcategory: "Pâtes",
    defaultWeight: 200,
    baseTime: 4,
    timePer100g: 0,
    method: "Eau",
    tips: ["Eau à peine frémissante", "Délicats"],
    emoji: "🍝"
  },
  {
    id: "pates-farfalle",
    name: "Farfalle",
    category: "Féculents",
    subcategory: "Pâtes",
    defaultWeight: 100,
    baseTime: 11,
    timePer100g: 0,
    method: "Eau",
    tips: ["Forme papillon", "Salades de pâtes"],
    emoji: "🍝"
  },

  // ═══════════════════════════════════════════════════════════════
  // FÉCULENTS - RIZ
  // ═══════════════════════════════════════════════════════════════
  {
    id: "riz-basmati",
    name: "Riz Basmati",
    category: "Féculents",
    subcategory: "Riz",
    defaultWeight: 60,
    baseTime: 11,
    timePer100g: 0,
    method: "Absorption",
    tips: ["Rincer avant", "1 vol. riz / 1.5 vol. eau"],
    emoji: "🍚"
  },
  {
    id: "riz-thai",
    name: "Riz Thaï",
    category: "Féculents",
    subcategory: "Riz",
    defaultWeight: 60,
    baseTime: 12,
    timePer100g: 0,
    method: "Absorption",
    tips: ["Parfumé au jasmin"],
    emoji: "🍚"
  },
  {
    id: "riz-risotto",
    name: "Riz Arborio (Risotto)",
    category: "Féculents",
    subcategory: "Riz",
    defaultWeight: 80,
    baseTime: 18,
    timePer100g: 0,
    method: "Cocotte",
    tips: ["Bouillon louche par louche", "Remuer constamment"],
    emoji: "🍚"
  },
  {
    id: "riz-complet",
    name: "Riz Complet",
    category: "Féculents",
    subcategory: "Riz",
    defaultWeight: 60,
    baseTime: 35,
    timePer100g: 0,
    method: "Eau",
    tips: ["Plus long à cuire", "Plus nutritif"],
    emoji: "🍚"
  },
  {
    id: "riz-sushi",
    name: "Riz à Sushi",
    category: "Féculents",
    subcategory: "Riz",
    defaultWeight: 100,
    baseTime: 15,
    timePer100g: 0,
    method: "Absorption",
    tips: ["Rincer plusieurs fois", "Vinaigre de riz après"],
    emoji: "🍚"
  },

  // ═══════════════════════════════════════════════════════════════
  // FÉCULENTS - CÉRÉALES
  // ═══════════════════════════════════════════════════════════════
  {
    id: "quinoa",
    name: "Quinoa",
    category: "Féculents",
    subcategory: "Céréales",
    defaultWeight: 80,
    baseTime: 12,
    timePer100g: 0,
    method: "Absorption",
    tips: ["Rincer abondamment", "1 vol. quinoa / 2 vol. eau"],
    emoji: "🌾"
  },
  {
    id: "boulgour",
    name: "Boulgour",
    category: "Féculents",
    subcategory: "Céréales",
    defaultWeight: 80,
    baseTime: 10,
    timePer100g: 0,
    method: "Absorption",
    tips: ["Gonfle dans l'eau chaude", "Base de taboulé"],
    emoji: "🌾"
  },
  {
    id: "couscous",
    name: "Couscous",
    category: "Féculents",
    subcategory: "Céréales",
    defaultWeight: 80,
    baseTime: 5,
    timePer100g: 0,
    method: "Vapeur",
    tips: ["Eau bouillante + repos", "Égrener à la fourchette"],
    emoji: "🌾"
  },
  {
    id: "polenta",
    name: "Polenta",
    category: "Féculents",
    subcategory: "Céréales",
    defaultWeight: 100,
    baseTime: 30,
    timePer100g: 0,
    method: "Eau",
    tips: ["Verser en pluie", "Remuer sans cesse"],
    emoji: "🌾"
  },
  {
    id: "semoule",
    name: "Semoule",
    category: "Féculents",
    subcategory: "Céréales",
    defaultWeight: 80,
    baseTime: 5,
    timePer100g: 0,
    method: "Absorption",
    tips: ["Eau bouillante", "Couvrir et laisser gonfler"],
    emoji: "🌾"
  },

  // ═══════════════════════════════════════════════════════════════
  // OEUFS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "oeuf-dur",
    name: "Oeuf Dur",
    category: "Oeufs",
    subcategory: "Entier",
    defaultWeight: 60,
    baseTime: 9,
    timePer100g: 0,
    method: "Eau",
    tips: ["Plonger dans eau bouillante", "Refroidir immédiatement"],
    emoji: "🥚"
  },
  {
    id: "oeuf-mollet",
    name: "Oeuf Mollet",
    category: "Oeufs",
    subcategory: "Entier",
    defaultWeight: 60,
    baseTime: 6,
    timePer100g: 0,
    method: "Eau",
    tips: ["Blanc cuit, jaune coulant", "Délicat à écaler"],
    emoji: "🥚"
  },
  {
    id: "oeuf-coque",
    name: "Oeuf à la Coque",
    category: "Oeufs",
    subcategory: "Entier",
    defaultWeight: 60,
    baseTime: 3,
    timePer100g: 0,
    method: "Eau",
    tips: ["Servir immédiatement", "Avec mouillettes"],
    emoji: "🥚"
  },
  {
    id: "oeuf-poche",
    name: "Oeuf Poché",
    category: "Oeufs",
    subcategory: "Entier",
    defaultWeight: 60,
    baseTime: 3,
    timePer100g: 0,
    method: "Eau",
    tips: ["Eau frémissante + vinaigre", "Créer un tourbillon"],
    emoji: "🥚"
  },
  {
    id: "oeuf-plat",
    name: "Oeuf au Plat",
    category: "Oeufs",
    subcategory: "Entier",
    defaultWeight: 60,
    baseTime: 3,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Feu doux", "Blanc cuit, jaune coulant"],
    emoji: "🍳"
  },
  {
    id: "oeufs-brouilles",
    name: "Oeufs Brouillés",
    category: "Oeufs",
    subcategory: "Battus",
    defaultWeight: 120,
    baseTime: 5,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Feu très doux", "Remuer constamment, crémeux"],
    emoji: "🍳"
  },
  {
    id: "omelette",
    name: "Omelette",
    category: "Oeufs",
    subcategory: "Battus",
    defaultWeight: 120,
    baseTime: 3,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Feu vif au début", "Baveuse au centre"],
    emoji: "🍳"
  },
  {
    id: "quiche",
    name: "Quiche Lorraine",
    category: "Oeufs",
    subcategory: "Tartes",
    defaultWeight: 800,
    baseTime: 35,
    timePer100g: 0,
    method: "Four",
    temp: 180,
    tips: ["Appareil: oeufs + crème", "Lardons et gruyère"],
    emoji: "🥧"
  },
  {
    id: "souffle-fromage",
    name: "Soufflé au Fromage",
    category: "Oeufs",
    subcategory: "Soufflés",
    defaultWeight: 400,
    baseTime: 25,
    timePer100g: 0,
    method: "Four",
    temp: 200,
    tips: ["Ne pas ouvrir le four", "Servir immédiatement"],
    emoji: "🧁"
  },
  {
    id: "frittata",
    name: "Frittata",
    category: "Oeufs",
    subcategory: "Battus",
    defaultWeight: 300,
    baseTime: 15,
    timePer100g: 0,
    method: "Four",
    temp: 180,
    tips: ["Commencer à la poêle", "Finir au four"],
    emoji: "🍳"
  },

  // ═══════════════════════════════════════════════════════════════
  // FRUITS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "pommes",
    name: "Pommes",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 200,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Fraîches et croquantes"],
    emoji: "🍎"
  },
  {
    id: "pommes-poelees",
    name: "Pommes Poêlées",
    category: "Fruits",
    subcategory: "Fruits Cuits",
    defaultWeight: 300,
    baseTime: 10,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Beurre et sucre", "Quartiers dorés"],
    emoji: "🍎"
  },
  {
    id: "pommes-au-four",
    name: "Pommes au Four",
    category: "Fruits",
    subcategory: "Fruits Cuits",
    defaultWeight: 200,
    baseTime: 30,
    timePer100g: 0,
    method: "Four",
    temp: 180,
    tips: ["Évider le coeur", "Beurre, sucre, cannelle"],
    emoji: "🍎"
  },
  {
    id: "compote-pommes",
    name: "Compote de Pommes",
    category: "Fruits",
    subcategory: "Fruits Cuits",
    defaultWeight: 500,
    baseTime: 20,
    timePer100g: 0,
    method: "Cocotte",
    tips: ["Peu d'eau", "Écraser ou mixer"],
    emoji: "🍎"
  },
  {
    id: "poires",
    name: "Poires",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 200,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Mûres à point"],
    emoji: "🍐"
  },
  {
    id: "poires-pochees",
    name: "Poires Pochées",
    category: "Fruits",
    subcategory: "Fruits Cuits",
    defaultWeight: 400,
    baseTime: 25,
    timePer100g: 0,
    method: "Eau",
    tips: ["Sirop vanillé ou vin rouge", "Tendres à coeur"],
    emoji: "🍎"
  },
  {
    id: "bananes",
    name: "Bananes",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 150,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Bien mûres pour plus de sucre"],
    emoji: "🍌"
  },
  {
    id: "bananes-flambees",
    name: "Bananes Flambées",
    category: "Fruits",
    subcategory: "Fruits Cuits",
    defaultWeight: 200,
    baseTime: 5,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Rhum ou cognac", "Caraméliser au sucre"],
    emoji: "🍎"
  },
  {
    id: "ananas",
    name: "Ananas",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 300,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Frais et juteux"],
    emoji: "🍍"
  },
  {
    id: "ananas-caramelise",
    name: "Ananas Caramélisé",
    category: "Fruits",
    subcategory: "Fruits Cuits",
    defaultWeight: 300,
    baseTime: 8,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Tranches épaisses", "Caramel et rhum"],
    emoji: "🍎"
  },
  {
    id: "peches",
    name: "Pêches",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 200,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Parfumées et juteuses"],
    emoji: "🍑"
  },
  {
    id: "peches-poelees",
    name: "Pêches Poêlées",
    category: "Fruits",
    subcategory: "Fruits Cuits",
    defaultWeight: 300,
    baseTime: 5,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Demi-pêches", "Beurre et sucre vanillé"],
    emoji: "🍎"
  },
  {
    id: "abricots",
    name: "Abricots",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 200,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Mûrs et parfumés"],
    emoji: "🍑"
  },
  {
    id: "abricots-rotis",
    name: "Abricots Rôtis",
    category: "Fruits",
    subcategory: "Fruits Cuits",
    defaultWeight: 300,
    baseTime: 15,
    timePer100g: 0,
    method: "Four",
    temp: 200,
    tips: ["En moitiés", "Miel et amandes"],
    emoji: "🍎"
  },
  {
    id: "figues",
    name: "Figues",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 150,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Fraîches et sucrées"],
    emoji: "🫐"
  },
  {
    id: "figues-roties",
    name: "Figues Rôties",
    category: "Fruits",
    subcategory: "Fruits Cuits",
    defaultWeight: 300,
    baseTime: 15,
    timePer100g: 0,
    method: "Four",
    temp: 180,
    tips: ["Inciser en croix", "Miel et mascarpone"],
    emoji: "🍎"
  },
  {
    id: "fraises",
    name: "Fraises",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 250,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["À température ambiante", "Sucrer légèrement"],
    emoji: "🍓"
  },
  {
    id: "framboises",
    name: "Framboises",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 150,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Délicates", "Ne pas laver si possible"],
    emoji: "🫐"
  },
  {
    id: "fruits-rouges",
    name: "Fruits Rouges Mélangés",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 300,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Frais ou surgelés", "Base de coulis"],
    emoji: "🍓"
  },
  {
    id: "fruits-rouges-poeles",
    name: "Fruits Rouges Poêlés",
    category: "Fruits",
    subcategory: "Fruits Cuits",
    defaultWeight: 300,
    baseTime: 3,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Feu doux", "Sucre et beurre, ne pas trop cuire"],
    emoji: "🍎"
  },
  {
    id: "rhubarbe",
    name: "Rhubarbe",
    category: "Fruits",
    subcategory: "Fruits Cuits",
    defaultWeight: 400,
    baseTime: 15,
    timePer100g: 0,
    method: "Cocotte",
    tips: ["Sucrer généreusement", "Fond facilement"],
    emoji: "🌿"
  },
  {
    id: "mangue",
    name: "Mangue",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 200,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Mûre et parfumée"],
    emoji: "🥭"
  },
  {
    id: "mangue-caramelisee",
    name: "Mangue Caramélisée",
    category: "Fruits",
    subcategory: "Fruits Cuits",
    defaultWeight: 200,
    baseTime: 4,
    timePer100g: 0,
    method: "Poêle",
    tips: ["Tranches épaisses", "Citron vert"],
    emoji: "🍎"
  },
  {
    id: "citron",
    name: "Citron",
    category: "Fruits",
    subcategory: "Agrumes",
    defaultWeight: 100,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Jus et zeste", "Indispensable en cuisine"],
    emoji: "🍋"
  },
  {
    id: "orange",
    name: "Orange",
    category: "Fruits",
    subcategory: "Agrumes",
    defaultWeight: 200,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Jus frais", "Zeste parfumé"],
    emoji: "🍊"
  },
  {
    id: "pruneaux",
    name: "Pruneaux",
    category: "Fruits",
    subcategory: "Fruits Secs",
    defaultWeight: 200,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Moelleux", "Accompagne viandes"],
    emoji: "🫐"
  },
  {
    id: "pruneaux-cuits",
    name: "Pruneaux au Vin",
    category: "Fruits",
    subcategory: "Fruits Cuits",
    defaultWeight: 300,
    baseTime: 20,
    timePer100g: 0,
    method: "Cocotte",
    tips: ["Vin rouge ou thé", "Gonfler et parfumer"],
    emoji: "🍎"
  },
  {
    id: "raisins",
    name: "Raisins",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 200,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Frais et sucrés", "Blanc ou noir"],
    emoji: "🍇"
  },
  {
    id: "melon",
    name: "Melon",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 300,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Bien mûr", "Rafraîchir avant de servir"],
    emoji: "🍈"
  },
  {
    id: "pasteque",
    name: "Pastèque",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 400,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Très rafraîchissante", "Servir bien froide"],
    emoji: "🍉"
  },
  {
    id: "kiwi",
    name: "Kiwi",
    category: "Fruits",
    subcategory: "Fruits Crus",
    defaultWeight: 100,
    baseTime: 0,
    timePer100g: 0,
    method: "Cru",
    tips: ["Riche en vitamine C", "Mûr quand souple"],
    emoji: "🥝"
  }
];

export const CUISSON_MODES = {
  SAIGNANT: { label: "Saignant", multiplier: 1 },
  A_POINT: { label: "À point", multiplier: 1.2 },
  BIEN_CUIT: { label: "Bien cuit", multiplier: 1.5 },
  AL_DENTE: { label: "Al Dente", multiplier: 1 },
  FONDANT: { label: "Fondant", multiplier: 1.3 }
};

INGREDIENTS.forEach(ing => {
  if (!ing.image_url) {
    ing.image_url = getImageUrl(ing.id);
  }
});
